# Establece la imagen base
FROM node:lts as build

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos del proyecto e instala dependencias
COPY . .

RUN rm -rf node_modules

RUN npm ci

RUN npm run build

## Configuramos un servidor nginx con un reverse proxy para la app
FROM nginx:stable-alpine

COPY --from=build /app/build /usr/share/nginx/html
# new
COPY .docker/nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
