# Establece la imagen base
FROM node:18 as build

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos del proyecto e instala dependencias
COPY . .

RUN npm ci
RUN npm run build

RUN rm -rf node_modules

RUN npm ci --omit=dev


## Configuramos un servidor nginx con un reverse proxy para la app
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
# new
COPY .docker/nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
