# Establece la imagen base
FROM node:18

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos del proyecto e instala dependencias
COPY . .

RUN npm ci
RUN npm run build

RUN rm -rf node_modules

RUN npm ci --omit=dev

WORKDIR /app/out

# Inicia la aplicación
ENTRYPOINT ["node", "app.js"]
