# Establece la imagen base
FROM node:18

# Establece el directorio de trabajo
WORKDIR /app

# Copia los archivos del proyecto e instala dependencias
COPY package*.json ./
RUN npm ci --omit=dev

COPY . .

# Inicia la aplicación
ENTRYPOINT ["npm", "run", "pro"]
